import type { Metadata } from 'next';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import QueryProvider from '@/components/QueryProvider';

import './globals.css';

export const metadata: Metadata = {
  title: 'Demolution Club',
  description: 'Generated by create next app',
  icons: '/favicon.ico',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='flex flex-col min-h-screen'>
        <QueryProvider>
          <Header />
          <main className='flex-grow'>{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
