# Generated by Django 5.2 on 2025-04-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_description_blog_preview_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.URLField(blank=True, default='/default-blog.png'),
        ),
    ]
